spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true