spring:
  datasource:
    druid:
      username: root
      password: 378024053a*1
      url: jdbc:mysql://rm-wz99j47vts9467b4e.mysql.rds.aliyuncs.com:3306/houses_single?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 30
      min-idle: 5
      max-wait: 10000
      validation-query: SELECT 'x'
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  freemarker:
    content-type: text/html;charset=UTF-8
    charset: utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      auto_import: common/common.ftl as common
  boot:
    admin:
      url: http://localhost:8070
  mail:
    host: smtp.qq.com
    port: 465
    username: 378024053@qq.com
    password: siupikirvjarbhch
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true
  output:
    ansi:
      enabled: always
server:
  port: 8091
mybatis:
  type-aliases-package: com.liaozan.common.model
  mapper-locations: mybatis/mapper/*.xml
customerApplication:
  config:
    domain: 129.79.7.142:8091
    savapath: /usr/developer/images
    nginxserverprefix: http://120.79.7.142:8081/images

