spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
customerapplication:
  config:
    domain: 129.79.7.142:8091
    savapath: /usr/developer/images
    nginxserverprefix: http://120.79.7.142:8081/images
    redis-server-url: 129.79.7.142