spring:
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/houses_danti?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 30
      min-idle: 5
      max-wait: 10000
      validation-query: SELECT 'x'
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  freemarker:
    content-type: text/html;charset=UTF-8
    charset: utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      auto_import: common/common.ftl as common
  boot:
    admin:
      url: http://localhost:8070
  mail:
    host: smtp.qq.com
    username: 378024053@qq.com
    password: siupikirvjarbhch
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  output:
    ansi:
      enabled: always
domain:
  name: 127.0.0.1:8091
file:
  path: F:\imgs
  prefix: http://127.0.0.1:8081/images
server:
  port: 8091
management:
  port: 8092
mybatis:
  type-aliases-package: com.liaozan.common.model
  mapper-locations: mybatis/mapper/*.xml
